In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML Engineering/Disease Prediction/dataset (1).csv')
df

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements,loss_of_balance,unsteadiness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4916,Acne,skin_rash,pus_filled_pimples,blackheads,scurring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4917,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4918,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4919,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose,yellow_crust_ooze,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#it means every column contain atleast one value
#because number of null values in last colums is less than the total number of rows

df['Symptom_17'].notnull().sum()

72

# **Get all the unique Diseases and Symptoms**

Remove the spaces between names

In [ ]:
def remove_space_between_word(dataset):
    for col in dataset.columns:
        for i in range(len(dataset[col])):
            if (type(dataset[col][i]) == str ):
                dataset[col][i] = dataset[col][i].strip()
                dataset[col][i] = dataset[col][i].replace(" ", "_")
    return df

In [ ]:
new_df = remove_space_between_word(df)
new_df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal_infection,itching,skin_rash,nodal_skin_eruptions,dischromic__patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal_infection,skin_rash,nodal_skin_eruptions,dischromic__patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal_infection,itching,nodal_skin_eruptions,dischromic__patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal_infection,itching,skin_rash,dischromic__patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal_infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Get all the Diseases in a list

In [ ]:
unique_disease = new_df['Disease'].unique()

In [ ]:
print(type(list(unique_disease)))

<class 'list'>

We got unique 41 Disease on which we will be doing prediction

In [ ]:
unique_disease

array(['Fungal_infection', 'Allergy', 'GERD', 'Chronic_cholestasis',
       'Drug_Reaction', 'Peptic_ulcer_diseae', 'AIDS', 'Diabetes',
       'Gastroenteritis', 'Bronchial_Asthma', 'Hypertension', 'Migraine',
       'Cervical_spondylosis', 'Paralysis_(brain_hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken_pox', 'Dengue', 'Typhoid', 'hepatitis_A',
       'Hepatitis_B', 'Hepatitis_C', 'Hepatitis_D', 'Hepatitis_E',
       'Alcoholic_hepatitis', 'Tuberculosis', 'Common_Cold', 'Pneumonia',
       'Dimorphic_hemmorhoids(piles)', 'Heart_attack', 'Varicose_veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo)_Paroymsal__Positional_Vertigo', 'Acne',
       'Urinary_tract_infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [ ]:
len(unique_disease)

41

Now get unique symptoms

In [ ]:
unique_symptoms = pd.unique(new_df.iloc[:, 1:].values.ravel('K'))
unique_symptoms

array(['itching', 'skin_rash', 'continuous_sneezing', 'shivering',
       'stomach_pain', 'acidity', 'vomiting', 'indigestion',
       'muscle_wasting', 'patches_in_throat', 'fatigue', 'weight_loss',
       'sunken_eyes', 'cough', 'headache', 'chest_pain', 'back_pain',
       'weakness_in_limbs', 'chills', 'joint_pain', 'yellowish_skin',
       'constipation', 'pain_during_bowel_movements', 'breathlessness',
       'cramps', 'weight_gain', 'mood_swings', 'neck_pain',
       'muscle_weakness', 'stiff_neck', 'pus_filled_pimples',
       'burning_micturition', 'bladder_discomfort', 'high_fever',
       'nodal_skin_eruptions', 'ulcers_on_tongue', 'loss_of_appetite',
       'restlessness', 'dehydration', 'dizziness',
       'weakness_of_one_body_side', 'lethargy', 'nausea',
       'abdominal_pain', 'pain_in_anal_region', 'sweating', 'bruising',
       'cold_hands_and_feets', 'anxiety', 'knee_pain', 'swelling_joints',
       'blackheads', 'foul_smell_of_urine', 'skin_peeling', 'blister',
       'dischromic__patches', 'watering_from_eyes',
       'extra_marital_contacts', 'diarrhoea', 'loss_of_balance',
       'blurred_and_distorted_vision', 'altered_sensorium', 'dark_urine',
       'swelling_of_stomach', 'bloody_stool', 'obesity', 'hip_joint_pain',
       'movement_stiffness', 'spinning_movements', 'scurring',
       'continuous_feel_of_urine', 'silver_like_dusting',
       'red_sore_around_nose', nan, 'spotting__urination',
       'passage_of_gases', 'irregular_sugar_level', 'family_history',
       'lack_of_concentration', 'excessive_hunger', 'yellowing_of_eyes',
       'distention_of_abdomen', 'irritation_in_anus', 'swollen_legs',
       'painful_walking', 'small_dents_in_nails', 'yellow_crust_ooze',
       'internal_itching', 'mucoid_sputum',
       'history_of_alcohol_consumption', 'swollen_blood_vessels',
       'unsteadiness', 'inflammatory_nails', 'depression',
       'fluid_overload', 'swelled_lymph_nodes', 'malaise',
       'prominent_veins_on_calf', 'puffy_face_and_eyes',
       'fast_heart_rate', 'irritability', 'muscle_pain', 'mild_fever',
       'yellow_urine', 'phlegm', 'enlarged_thyroid', 'increased_appetite',
       'visual_disturbances', 'brittle_nails', 'drying_and_tingling_lips',
       'polyuria', 'pain_behind_the_eyes', 'toxic_look_(typhos)',
       'throat_irritation', 'swollen_extremeties', 'slurred_speech',
       'red_spots_over_body', 'belly_pain', 'receiving_blood_transfusion',
       'acute_liver_failure', 'redness_of_eyes', 'rusty_sputum',
       'abnormal_menstruation', 'receiving_unsterile_injections', 'coma',
       'sinus_pressure', 'palpitations', 'stomach_bleeding', 'runny_nose',
       'congestion', 'blood_in_sputum', 'loss_of_smell'], dtype=object)

In [ ]:
len(unique_symptoms)

132

In [ ]:
unique_symptoms = list(unique_symptoms)

In [ ]:
#finding nan in unique_symptom
counter = 0
for i in unique_symptoms:
  if str(i) == 'nan':
    del unique_symptoms[counter]
  counter += 1
len(unique_symptoms)

131

# **One_Hot_Encoding**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

create dataset with only zero values

In [ ]:
d = pd.DataFrame(0, index=np.arange(len(df)), columns=unique_symptoms)
d

,itching,skin_rash,continuous_sneezing,shivering,stomach_pain,acidity,vomiting,indigestion,muscle_wasting,patches_in_throat,...,abnormal_menstruation,receiving_unsterile_injections,coma,sinus_pressure,palpitations,stomach_bleeding,runny_nose,congestion,blood_in_sputum,loss_of_smell
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4916,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4918,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4919,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

encoding the above dataset(replacing zeros with one when there is match)

In [ ]:
def one_hot_encode(df):
  for d1 in range(0,len(df)):
    #print(d1)
    for i in d.columns:
      #print(i)
      for x in range(0,17):
        find = df.iloc[d1, x]
        #print(find)
        if i == find:
          d.iloc[d1, d.columns.get_loc(i)] = 1

  return d

In [ ]:
df = one_hot_encode(df)

In [ ]:
all_disease = df['Disease']
all_disease = list(all_disease)

In [ ]:
encoded_dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML Engineering/Disease Prediction/one_hot_encoded1.csv', index_col=False)
encoded_dataset['Disease'] = all_disease

In [ ]:
encoded_dataset

,itching,skin_rash,continuous_sneezing,shivering,stomach_pain,acidity,vomiting,indigestion,muscle_wasting,patches_in_throat,...,receiving_unsterile_injections,coma,sinus_pressure,palpitations,stomach_bleeding,runny_nose,congestion,blood_in_sputum,loss_of_smell,Disease
0,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal_infection
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal_infection
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal_infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal_infection
4,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal_infection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo)_Paroymsal__Positional_Vertigo
4916,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Acne
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary_tract_infection
4918,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Psoriasis
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Impetigo

In [ ]:
encoded_dataset.to_csv("/content/drive/MyDrive/Colab Notebooks/ML Engineering/Disease Prediction/one_hot_encoded1.csv", index=False)

We need to RUN the above code only for once so now I have commented all that code

Now I have complete encoded dataset and I can start doing training using ML Algorithm

In [ ]:
encoded_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML Engineering/Disease Prediction/one_hot_encoded1.csv', index_col=False)
encoded_data

,itching,skin_rash,continuous_sneezing,shivering,stomach_pain,acidity,vomiting,indigestion,muscle_wasting,patches_in_throat,...,receiving_unsterile_injections,coma,sinus_pressure,palpitations,stomach_bleeding,runny_nose,congestion,blood_in_sputum,loss_of_smell,Disease
0,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal_infection
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal_infection
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal_infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal_infection
4,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal_infection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo)_Paroymsal__Positional_Vertigo
4916,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Acne
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary_tract_infection
4918,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Psoriasis
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Impetigo

In [ ]:
x = encoded_data[unique_symptoms]
# target values
y = encoded_data[["Disease"]]

In [ ]:
#x

,itching,skin_rash,continuous_sneezing,shivering,stomach_pain,acidity,vomiting,indigestion,muscle_wasting,patches_in_throat,...,abnormal_menstruation,receiving_unsterile_injections,coma,sinus_pressure,palpitations,stomach_bleeding,runny_nose,congestion,blood_in_sputum,loss_of_smell
0,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18531,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18532,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18533,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18534,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18535,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#y

                                      Diseases
0                             Fungal_infection
1                             Fungal_infection
2                             Fungal_infection
3                             Fungal_infection
4                             Fungal_infection
...                                        ...
18531  (vertigo)_Paroymsal__Positional_Vertigo
18532                                     Acne
18533                  Urinary_tract_infection
18534                                Psoriasis
18535                                 Impetigo

[18536 rows x 1 columns]

# **Random Forest Training**

In [ ]:
#!pip install -U scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (1.0.2)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.21.6)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.7.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (3.1.0)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
X_train

,itching,skin_rash,continuous_sneezing,shivering,stomach_pain,acidity,vomiting,indigestion,muscle_wasting,patches_in_throat,...,abnormal_menstruation,receiving_unsterile_injections,coma,sinus_pressure,palpitations,stomach_bleeding,runny_nose,congestion,blood_in_sputum,loss_of_smell
897,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
293,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4563,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4650,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3984,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1216,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1935,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1820,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4834,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1185,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
X_test

,itching,skin_rash,continuous_sneezing,shivering,stomach_pain,acidity,vomiting,indigestion,muscle_wasting,patches_in_throat,...,abnormal_menstruation,receiving_unsterile_injections,coma,sinus_pressure,palpitations,stomach_bleeding,runny_nose,congestion,blood_in_sputum,loss_of_smell
3876,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3472,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4622,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4691,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1201,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1848,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2290,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2602,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1017,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
446,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
y_train

                                      Disease
897                                  Diabetes
293                              Heart_attack
4563                     Cervical_spondylosis
4650                                   Dengue
3984                                 Diabetes
...                                       ...
1216                                Psoriasis
1935                             Heart_attack
1820                                  Typhoid
4834                                     Acne
1185  (vertigo)_Paroymsal__Positional_Vertigo

[3936 rows x 1 columns]

In [ ]:
y_test

                           Disease
3876                   Hepatitis_D
3472  Dimorphic_hemmorhoids(piles)
4622                Varicose_veins
4691                        Dengue
1201       Urinary_tract_infection
...                            ...
1848                   Hepatitis_B
2290           Alcoholic_hepatitis
2602                   hepatitis_A
1017                   hepatitis_A
446            Chronic_cholestasis

[984 rows x 1 columns]

Training

In [ ]:
random_forest_object = RandomForestClassifier(n_estimators=60)
random_forest_object.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

RandomForestClassifier(n_estimators=60)

In [ ]:
from sklearn.metrics import accuracy_score
y_pred = random_forest_object.predict(X_test)
print(accuracy_score(y_test, y_pred)*100)
print(accuracy_score(y_test, y_pred, normalize=False))